version: '2'

services:
  postgres:
      image: postgres:9.6
      ports:
        - "5432:5432"
      volumes_from:
        - data
      environment:
        - POSTGRES_DB=ddd_springboot
        - POSTGRES_USER=ddd_springboot
        - POSTGRES_PASSWORD=ddd_springboot
  data:
      image: cogniteev/echo
      command: echo 'Data Container for PostgreSQL'
      volumes:
        - /var/lib/postgresql/data